# Generated by Django 3.0.8 on 2020-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=200)),
                ('line_two', models.CharField(max_length=200)),
                ('line_three', models.CharField(max_length=500)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
