# Generated by Django 3.0.8 on 2020-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0002_auto_20200709_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=100)),
                ('line_two', models.CharField(max_length=100)),
                ('link_facebook', models.CharField(max_length=70)),
                ('link_instagram', models.CharField(max_length=70)),
                ('link_linkedin', models.CharField(max_length=70)),
                ('link_pinterest', models.CharField(max_length=70)),
                ('link_gmail', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('copyright_text', models.CharField(max_length=30)),
                ('copyright_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=100)),
                ('line_two', models.CharField(max_length=50)),
                ('line_three', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=50)),
                ('line_two', models.CharField(max_length=200)),
                ('line_three', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='index_header',
            name='line_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index_header',
            name='line_three',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index_header',
            name='line_two',
            field=models.CharField(max_length=150),
        ),
    ]
