# Generated by Django 3.0.8 on 2020-07-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0003_auto_20200709_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_content',
            name='line_two',
            field=models.CharField(max_length=300),
        ),
    ]
