# Generated by Django 3.0.8 on 2020-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0005_auto_20200709_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desctiption', models.CharField(max_length=500)),
                ('images', models.ImageField(upload_to='media')),
            ],
        ),
    ]
