# Generated by Django 3.0.8 on 2020-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0006_trainings_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_Content_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Enroll_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=60)),
                ('line_two', models.CharField(max_length=100)),
                ('line_three', models.CharField(max_length=100)),
                ('line_four', models.CharField(max_length=100)),
                ('line_five', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='media')),
                ('line_six', models.CharField(max_length=250)),
                ('instagram_account', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('link', models.CharField(max_length=60)),
            ],
        ),
    ]
