# Generated by Django 3.0.8 on 2020-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0009_template_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template_info',
            old_name='image',
            new_name='image_big',
        ),
        migrations.AddField(
            model_name='template_info',
            name='image_small',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='template_info',
            name='small_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
