# Generated by Django 3.0.8 on 2020-07-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0010_auto_20200709_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template_Info',
            new_name='Scholarship_Opportunitie',
        ),
    ]
