# Generated by Django 3.0.8 on 2020-07-09 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0015_opportunities_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_opportunitie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Opportunities_Category'),
        ),
        migrations.AlterField(
            model_name='scholarship_opportunitie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Opportunities_Category'),
        ),
    ]
