# Generated by Django 3.0.8 on 2020-07-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0016_auto_20200710_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitie',
            name='link',
            field=models.CharField(default='', max_length=20),
        ),
    ]
