# Generated by Django 3.0.8 on 2020-07-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0017_opportunitie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitie',
            name='link',
            field=models.CharField(default='', max_length=40),
        ),
    ]
