# Generated by Django 3.0.8 on 2020-07-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0018_auto_20200710_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_opportunitie',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scholarship_opportunitie',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
