# Generated by Django 3.0.8 on 2020-07-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0019_auto_20200710_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_opportunitie',
            name='category_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Opportunitie'),
        ),
    ]
