# Generated by Django 3.0.8 on 2020-07-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0020_program_opportunitie_category_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_A_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('opportunity_name', models.CharField(max_length=50)),
                ('opportunity_selected', models.CharField(max_length=100)),
            ],
        ),
    ]
