# Generated by Django 3.0.8 on 2020-07-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0021_call_a_mentor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Call_A_Mentor',
            new_name='Call_Mentor',
        ),
    ]
