# Generated by Django 3.0.8 on 2020-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0023_countrie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('training', models.CharField(max_length=30)),
            ],
        ),
    ]
