# Generated by Django 3.0.8 on 2020-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0025_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
