# Generated by Django 3.0.8 on 2020-07-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0027_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_opportunitie',
            name='founded_features',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='scholarship_opportunitie',
            name='founded_features',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
