# Generated by Django 3.0.8 on 2020-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0028_auto_20200713_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_content',
            name='line_three',
            field=models.CharField(max_length=300),
        ),
    ]
