# Generated by Django 3.0.8 on 2020-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0029_auto_20200715_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
