# Generated by Django 3.0.8 on 2020-07-16 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0030_auto_20200715_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings_page',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
