# Generated by Django 3.0.8 on 2020-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0031_trainings_page_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll_page',
            name='line_eight',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='enroll_page',
            name='line_seven',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
