# Generated by Django 3.0.8 on 2020-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0034_addtoprofile_program_addtoprofile_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
