# Generated by Django 3.0.8 on 2020-09-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0035_auto_20200910_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='surname',
        ),
    ]
