# Generated by Django 3.0.8 on 2020-09-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0041_auto_20200910_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='images',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
