# Generated by Django 3.0.8 on 2020-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0045_auto_20200910_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='registration_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mediaa'),
        ),
    ]
