# Generated by Django 3.0.8 on 2020-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0047_act_smart_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
