# Generated by Django 3.0.8 on 2020-09-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0048_premium_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
