# Generated by Django 3.0.8 on 2020-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0050_auto_20200910_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='registration_type',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='payed_for_premium_account',
            field=models.BooleanField(default='False'),
        ),
    ]
