# Generated by Django 3.0.8 on 2020-09-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0052_auto_20200910_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
