# Generated by Django 3.0.8 on 2020-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0054_order_premium_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='payed_for_premium_account',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='premium_account',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
    ]
