# Generated by Django 3.0.8 on 2020-09-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0055_auto_20200910_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='premium_account',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
