# Generated by Django 3.0.8 on 2020-09-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0056_auto_20200910_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='premium_account',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
