# Generated by Django 3.0.8 on 2020-09-11 11:11

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0058_auto_20200911_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_premium_account',
            name='date_expired',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
