# Generated by Django 3.0.8 on 2020-09-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0059_order_premium_account_date_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple_Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('features', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='premium_registration',
            name='features',
            field=models.TextField(default=''),
        ),
    ]
