# Generated by Django 3.0.8 on 2020-09-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0060_auto_20200912_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simple_Registrations',
            new_name='Simple_Registration',
        ),
    ]
