# Generated by Django 3.0.8 on 2020-09-13 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0062_mentorship_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('opportunity_name', models.CharField(max_length=50)),
                ('opportunity_selected', models.CharField(max_length=100)),
                ('product', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Premium_Registration')),
            ],
        ),
    ]
