# Generated by Django 3.0.8 on 2020-09-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0063_mentorship_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship_order',
            name='product',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Mentorship_Program'),
        ),
    ]
