# Generated by Django 3.0.8 on 2020-09-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0064_auto_20200913_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor_Features',
        ),
    ]
