# Generated by Django 3.0.8 on 2020-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0065_delete_mentor_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Enrolled',
        ),
    ]
