# Generated by Django 3.0.8 on 2020-09-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0066_auto_20200913_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training_Enrolled',
            new_name='Training_Enroll',
        ),
    ]
