# Generated by Django 3.0.8 on 2020-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0068_delete_trainings_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('images', models.ImageField(upload_to='media')),
                ('features', models.TextField(default='')),
                ('available', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('deadline', models.DateField()),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Trainings_Page',
        ),
    ]
