# Generated by Django 3.0.8 on 2020-09-15 08:14

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0070_training_enroll_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_enroll',
            name='date_register',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
