# Generated by Django 3.0.8 on 2020-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0071_training_enroll_date_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call_mentor',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='call_mentor',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
