# Generated by Django 3.0.8 on 2020-09-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0072_auto_20200915_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index_Header',
        ),
    ]
