# Generated by Django 3.0.8 on 2020-09-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0073_delete_index_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services_Content',
        ),
    ]
