# Generated by Django 3.0.8 on 2020-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0074_delete_services_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
