# Generated by Django 3.0.8 on 2020-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0075_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
