# Generated by Django 3.0.8 on 2020-11-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0076_opportunities_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor_Content',
        ),
    ]
