# Generated by Django 3.0.8 on 2020-11-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0077_delete_mentor_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll_Content_List',
        ),
    ]
