# Generated by Django 3.0.8 on 2020-11-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0078_delete_enroll_content_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll_Page',
        ),
    ]
