# Generated by Django 3.0.8 on 2020-11-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ActSmart', '0079_delete_enroll_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call_mentor',
            old_name='surname',
            new_name='opportunity_category',
        ),
        migrations.RemoveField(
            model_name='call_mentor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='call_mentor',
            name='opportunity_selected',
        ),
        migrations.AddField(
            model_name='call_mentor',
            name='date_register',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='call_mentor',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
