# Generated by Django 3.0.8 on 2020-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0082_booking_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('link', models.TextField(default='')),
            ],
        ),
    ]
