# Generated by Django 3.0.8 on 2020-11-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0084_auto_20201127_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countrie',
        ),
    ]
