# Generated by Django 3.0.8 on 2020-11-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0085_delete_countrie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity_Category_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Opportunities_Category')),
            ],
        ),
    ]
