# Generated by Django 3.0.8 on 2020-11-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0087_auto_20201128_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opportunities_Region',
        ),
    ]
