# Generated by Django 3.0.8 on 2020-11-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0088_delete_opportunities_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='link_gmail',
        ),
    ]
