# Generated by Django 3.0.8 on 2020-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0089_remove_footer_link_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='features',
        ),
        migrations.AddField(
            model_name='training',
            name='hours',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='training',
            name='language',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='training',
            name='small_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
