# Generated by Django 3.0.8 on 2020-11-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0090_auto_20201129_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
            ],
        ),
    ]
