# Generated by Django 3.0.8 on 2020-11-29 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0091_topic_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date_register', models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSmart.Training')),
            ],
        ),
        migrations.DeleteModel(
            name='Training_Enroll',
        ),
    ]
