# Generated by Django 3.0.8 on 2020-11-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0092_auto_20201129_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_opportunitie',
            name='category_two',
        ),
    ]
