# Generated by Django 3.0.8 on 2020-12-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSmart', '0093_remove_program_opportunitie_category_two'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Act_Smart_Product',
        ),
        migrations.RemoveField(
            model_name='order_premium_account',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_premium_account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mentorship_Order',
        ),
        migrations.DeleteModel(
            name='Mentorship_Program',
        ),
        migrations.DeleteModel(
            name='Order_Premium_Account',
        ),
    ]
